package Demo.API;

import Demo.Model.Product;
import Demo.Domain.ProductRepository;
import Demo.service.ProductService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping(value = "/products")
public class ProductAPI {
    @GetMapping(value = "/test")
    public String test() {

        return "OK " + "Alo " ;
    }
    @Autowired
    private ProductService productService;
    @GetMapping(value = "/all")
    public List getProducts() {
        return productService.getProducts();
    }
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository productRepository;
    @PostMapping(value = "/add")
   public @ResponseBody String AddProduct(@RequestBody Product product){

        productRepository.save(product);
        return product.getName();
    }
    @GetMapping(value = "/all/{id}")
    public Object getID(@PathVariable String id){
        return productService.getId(id);
    }
}
